name: Dozzle Agent
version: 1.0.5
slug: dozzle-agent
description: Dozzle agent per i log Docker
url: https://github.com/amarok77/hassio-addons/dozzle-agent
image: https://github.com/amir20/dozzle
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
ports:
  7007/tcp: 7007
ports_description:
  7007/tcp: Dozzle Agent API
docker_api: true
map:
  - docker_sock:ro
options: {}
schema: {}
