name: Dozzle Agent
version: 0.0.1
slug: dozzle-agent
description: Dozzle Agent
url: https://github.com/amir20/dozzle
image: amir20/dozzle:latest
arch:
  - armv7
  - aarch64
  - amd64
startup: service
boot: auto
init: false
command: agent
map:
  - /var/run/docker.sock:/var/run/docker.sock:ro
ports:
  7007/tcp: 7007
ports_description:
  7007/tcp: porta in ascolto agent
