name: Dozzle Beta
version: 0.1.2
slug: dozzle-beta
description: Container log viewer.
image: amir20/dozzle
url: https://dozzle.dev
arch:
- aarch64
- amd64
- armv7
- i386
startup: application
boot: auto
ports:
  - 8080/tcp: 8080
options:
schema:
webui: http://[HOST]:[PORT:8080]
