name: Neolink
version: 0.3.0
panel_icon: "mdi:cctv"
panel_title: Neolink
slug: neolink
description: An RTSP bridge to Reolink E1 IP camera
url: "https://github.com/thirtythreeforty/neolink"
image: ghcr.io/thirtythreeforty/neolink
startup: application
boot: auto
init: false
#webui: "http://[HOST]:[PORT:5000]/"
#watchdog: "http://[HOST]:[PORT:5000]/"
#ingress: true
#ingress_port: 5000
#ingress_entry: /
#panel_admin: false
#homeassistant_api: true
#hassio_api: true
name: "Reolink E1"
username: "admin"
password: "12345678"
address: "192.168.1.187:9000"
