version: "3.9"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    enviroment:
      - DOZZLE_USERNAME=admin
      - DOZZLE_PASSWORD=password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    option:
      users:
        admin: "Admin"
        password: "password"
        email: caltaste@inwind.it
    schema:
      timezone: str
      admin_user: str
      admin_password: str
      log_level: list(trace|debug|info|notice|warning|error|fatal)?
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
