name: Dozzle
version: 1.2
slug: dozzle
description: Dozzle is a Log viewer designed to simplify the process of monitoring and debugging containers.
url: https://github.com/amir20/dozzle
arch:
- aarch64
- amd64
- armv7
- armhf
- i386
stage: experimental
init: false
panel_icon: mdi:user
service:
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
