name: Dozzle
version: 6.2.4
slug: dozzle
description: Container log viewer
url: https://github.com/amarok77/hassio-addons
arch:
- aarch64
- amd64
- armv7
- i386
init: false
ingress: true
#ingress_stream: true
panel_icon: mdi:binoculars
map:
- ssl
#services:
#- mysql:need
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: HTTP
hassio_api: false
options:
  #my_hostname: mydomain.no-ip.com
  #domain_name: mydomain.no-ip.com
  admin_user: admin
  admin_password: null
  #letsencrypt_certs: false
  #enable_mailfilter: false
  #message_size_limit: 10
schema:
  #my_hostname: str
  #domain_name: str
  admin_user: str
  admin_password: str
  #letsencrypt_certs: bool
  #enable_mailfilter: bool
  #smtp_relayhost: str?
  #smtp_relayhost_credentials: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  #message_size_limit: int
image: "amir20/dozzle"
webui: "http://localhost:[PORT:8080]"
