name: Dozzle
version: 3
slug: dozzle
description: Dozzle is a Log viewer designed to simplify the process of monitoring and debugging containers.
url: https://github.com/amarok77/addon-dozzle
arch:
- amd64
stage: experimental
init: false
panel_icon: mdi:log
map:
- ssl
service:
  dozzle:
    container_name: dozzle
    image: amir20/doozle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Dozzle TCP port
hassio_api: true
option:
  timezone: CET
  admin_user: admin
  admin_password: admin
schema:
  timezone: str
  admin_user: str
  admin_password: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/amarok77/dozzle/amd64