name: Dozzle
version: 1.2
slug: dozzle
description: Dozzle is a Log viewer designed to simplify the process of monitoring and debugging containers.
url: https://github.com/amir20/dozzle
arch:
- aarch64
- amd64
- armv7
- armhf
- i386
stage: experimental
init: false
panel_icon: mdi:user
service:
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Dozzle TCP port
option:
  users:
    admin: "Admin"
    password: "password"
    email: caltaste@inwind.it
schema:
  timezone: str
  admin_user: str
  admin_password: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
